name: Dispatch workflow

on:
  workflow_call:
    inputs:
      trigger:
        required: true
        type: string
    secrets:
      token:
        required: false
  
jobs:
  Event_Print:
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}

  Feature_Branch:
    needs: [Event_Print]
    if: (github.event_name == 'push')
    uses: gabor-kovac/workflow/.github/workflows/feature_branch.yml@main
    secrets: inherit

  # Release_Candidate:
  #   needs: [Event_Print]
  #   if: (github.event_name == 'pull_request' && github.base_ref == 'main' && github.event.pull_request.merged == true)
  #   uses: gabor-kovac/workflow/.github/workflows/release_candidate.yml@main
  #   secrets: inherit
    
  # Release:
  #   needs: [Event_Print]
  #   if: (github.event_name == 'pull_request' && github.base_ref == 'release' && github.head_ref == 'main' && github.event.pull_request.merged == true)
  #   uses: gabor-kovac/workflow/.github/workflows/release.yml@main
  #   secrets: inherit
