name: Dispatch workflow

on:
  workflow_call:
    inputs:
      trigger:
        required: true
        type: string
    secrets:
      token:
        required: false

jobs:
  Event_Print:
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
        
  Pull_Request:
    needs: [Event_Print]
    if: (github.event_name == 'pull_request')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by pull request"

  Push:
    needs: [Event_Print]
    if: (github.event_name == 'push')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by push"

  
