name: Update feature branch

on:
  workflow_call:
    secrets:
      token: 
        required: false
        
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write

jobs:
  Increase_Version_TypeScript:
    if: (github.event.repository.language == 'TypeScript' || github.event.repository.language == 'Dockerfile')
    runs-on: ubuntu-latest
    outputs:
      newVersion: ${{ steps.package_version.outputs.new-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump patch version
        id: package_version
        uses: gedclack/simple-bump-package-json@v1.0.0
        with:
          bump-mode: patch
          
      - name: Commit new version
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "CI: bump package version to ${{ steps.package_version.outputs.new-version }}"
          git push

  # Update_Status_Tracker:
  #   needs: [Increase_Version_TypeScript]
  #   uses: gabor-kovac/workflow/.github/workflows/create_and_commit_repo_info.yml@main
  #   secrets: inherit

  Create_Artifact:
    needs: [Increase_Version_TypeScript]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4 
      
      - name: Pull all changes 
        run: git pull
        
      - name: Lowercase the name of the repository 
        id: LowercaseRepositoryName
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.event.repository.name }}
      
      - name: Get the name of the current branch
        id: GetCurrentBranchName
        uses: tj-actions/branch-names@v8
            
      - name: Login to the GitHub Container regsitry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Build docker image (C# projects)
        if: (github.event.repository.language == 'C#')
        working-directory: ./Source
        run: |
          docker build --push --platform linux/amd64 --tag ghcr.io/gabor-kovac/${{ steps.LowercaseRepositoryName.outputs.lowercase }}:${{ inputs.assemblyVersion }}-${{ steps.GetCurrentBranchName.outputs.current_branch }} --file ./Dockerfile --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" .

      - name: Build docker image (TypeScript projects) 
        if: (github.event.repository.language == 'TypeScript' || github.event.repository.language == 'Dockerfile')
        run: |
          docker build --platform linux/amd64 --tag ghcr.io/gabor-kovac/${{ steps.LowercaseRepositoryName.outputs.lowercase }}:${{ needs.Increase_Version_TypeScript.outputs.newVersion }}-${{ steps.GetCurrentBranchName.outputs.current_branch }} --file ./Dockerfile --output=type=registry --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" .
