name: Update feature branch

on:
  workflow_call:
    secrets:
      token: 
        required: false
        
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  Increase_Version_TypeScript:
    if: (github.event.repository.language == 'TypeScript')
    runs-on: ubuntu-latest
    outputs:
      newVersion: ${{ steps.increase_package_version.outputs.next-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump patch version
        id: package_version
        uses: KageKirin/bump-node-package-version@v1
        with:
          patch: true
          
      - name: Commit new version
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "CI: bump package version to ${{ steps.package_version.version }}"
          git push
  
