name: Create release candidate

on:
  workflow_call:
    secrets:
      token: 
        required: false
        
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write

jobs:
  Increase_Version_TypeScript:
    if: (github.event.repository.language == 'TypeScript' || github.event.repository.language == 'Dockerfile')
    runs-on: ubuntu-latest
    outputs:
      newVersion: ${{ steps.package_version.outputs.new-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump patch version
        id: package_version
        uses: gedclack/simple-bump-package-json@v1.0.0
        with:
          bump-mode: major
          
      - name: Commit new version
        run: |
          git pull
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "CI: bump package version to ${{ steps.package_version.outputs.new-version }}"
          git push -u

  Create_Artifact:
    needs: [Increase_Version_TypeScript]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout main branch
        if: (github.event_name == 'pull_request' && github.base_ref == 'release')
        uses: actions/checkout@v4
        with: 
          ref: '${{github.head_ref}}'
      
      - name: Pull all changes 
        run: git pull
        
      - name: Lowercase the name of the repository 
        id: LowercaseRepositoryName
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.event.repository.name }}
      
      - name: Get the name of the current branch
        id: GetCurrentBranchName
        uses: tj-actions/branch-names@v8
            
      - name: Login to the GitHub Container regsitry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image (TypeScript projects)
        if: ((github.event.repository.language == 'TypeScript' || github.event.repository.language == 'Dockerfile') && github.event_name == 'pull_request' )
        run: |
          docker build --platform linux/amd64 --tag ghcr.io/gabor-kovac/${{ steps.LowercaseRepositoryName.outputs.lowercase }}:${{ needs.Increase_Version_TypeScript.outputs.newVersion }} --file ./Dockerfile --output=type=registry --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" .

      - name: Create tag (TypeScript)
        if: (github.event_name == 'pull_request' && github.base_ref == 'main' && (github.event.repository.language == 'TypeScript' || github.event.repository.language == 'Dockerfile') || github.event_name == 'pull_request' && github.base_ref == 'release' && (github.event.repository.language == 'TypeScript' || github.event.repository.language == 'Dockerfile'))
        id: CreateTagFromPackageJsonVersion
        uses: mathieudutour/github-tag-action@v6.1
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            custom_tag: ${{ needs.Increase_Version_TypeScript.outputs.newVersion }}
            tag_prefix: " "

      - name: Create a GitHub release
        if: ( github.event_name == 'pull_request' && github.base_ref == 'release' && (github.event.repository.language == 'TypeScript' || github.event.repository.language == 'Dockerfile') )
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ needs.Increase_Version_TypeScript.outputs.newVersion }}
          name: Release ${{ needs.Increase_Version_TypeScript.outputs.newVersion }}

      - name: Generate SBOM for release (TypeScript)
        if: (github.event_name == 'pull_request' && github.base_ref == 'release' && (github.event.repository.language == 'TypeScript' || github.event.repository.language == 'Dockerfile'))
        uses: anchore/sbom-action@v0.20.2
        with:
          image: ghcr.io/gabor-kovac/${{ steps.LowercaseRepositoryName.outputs.lowercase }}:${{ needs.Increase_Version_TypeScript.outputs.newVersion }}
          format: spdx-json
          output-file: sbom.spdx.json
          upload-release-assets: true
