name: Test Workflow

on:
  workflow_call:
    secrets:
      token:
        required: false
    inputs:
      override:
        type: string
        required: false
        default: 'false'

jobs:
  What_Was_Trigger:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trigger was ${{ github.event_name }}"
        if: ${{ inputs.override != 'false' }}
        env:
          github.event_name: pull_request2

      - run: echo "Trigger was ${{ github.event_name }}"
        if: ${{ inputs.override == 'false' }}

      - run: echo "Trigger was ${{ github.event_name }}"
