name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      override:
        type: string
        required: false
        default: 'false'

jobs:
  What_Was_Trigger:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trigger was ${{ github.event_name }}"
        if: ${{ inputs.override != 'false' }}
        env:
          GITHUB_EVENT_NAME: pull_request2

      - run: echo "Trigger was ${{ github.event_name }}"
        if: ${{ inputs.override == 'false' }}

      - run: echo "Trigger was ${{ github.event_name }}"
